import { Collapsible } from "./collapsible";
import { ColorPicker } from "./color-picker";
import { ShinyDataGridOutput } from "./datagrid";
import { DesignPreview } from "./design-preview";
import { Footer } from "./footer";
import { GeneralOutput } from "./general-output";
import { Grid } from "./grid";
import { GridItem } from "./grid-item";
import { PositLogo } from "./posit-logo";
import { ShinyCard } from "./shiny-card";
import { ShinyDashboard } from "./shiny-dashboard";
import { Section } from "./shiny-section";
import { Sidebar } from "./sidebar";
import { SimpleNumberInput } from "./simple-number-input";
import { SimpleNumberOutput } from "./simple-number-output";
import { Tab } from "./tab";
import { Tabset } from "./tabset";
import { TanstackTable } from "./tanstack-table";
import { ThemeChooser } from "./theme-chooser";

import { ShinyIcon } from "./icon";
import { ShinyAvatar } from "./shiny-avatar";
import { TabsetLogip } from "./tabset-logip";

// Prevent esbuild from tree-shaking these components away.
Collapsible;
ColorPicker;
ShinyDataGridOutput;
DesignPreview;
Footer;
GeneralOutput;
Sidebar;
SimpleNumberInput;
SimpleNumberOutput;
Tab;
Tabset;
ShinyDashboard;
TanstackTable;
ThemeChooser;
Grid;
GridItem;
PositLogo;
ShinyCard;
Section;
TabsetLogip;
ShinyIcon;
ShinyAvatar;
