import { ForgeDarkModeSwitch } from "./dark-mode-switch";
import { ForgeInputActionButton } from "./input-action-button";
import { ForgeInputCheckbox } from "./input-checkbox";
import { ForgeInputCheckboxGroup } from "./input-checkbox-group";
import { ForgeInputDate } from "./input-date";
import { ForgeInputNumber } from "./input-number";
import { ForgeInputRadioButtons } from "./input-radio-buttons";
import { ForgeInputSelect } from "./input-select";
import { ForgeInputSlider } from "./input-slider";
import { ForgeInputSwitch } from "./input-switch";
import { ForgeInputText } from "./input-text";
import { ForgeInputTextArea } from "./input-text-area";
import { ForgeInputTime } from "./input-time";
import { ForgeOutputTextVerbatim } from "./output-text-verbatim";

// Prevent esbuild from tree-shaking these components away.
ForgeDarkModeSwitch;
ForgeInputActionButton;
ForgeInputCheckbox;
ForgeInputCheckboxGroup;
ForgeInputDate;
ForgeInputNumber;
ForgeInputRadioButtons;
ForgeInputSelect;
ForgeInputSlider;
ForgeInputSwitch;
ForgeInputText;
ForgeInputTextArea;
ForgeInputTime;
ForgeOutputTextVerbatim;
